Add AC_USE_SYSTEM_EXTENSIONS to expose non-standard extensions
Required on Solaris to expose fd_mask in <sys/select.h> now that
xtrans 1.3 defines _XOPEN_SOURCE to 600 on Solaris, since fd_mask
is not defined in that version of the XPG standards.

Fixes build failure:
../../src/FSConnServ.c: In function '_FSWaitForWritable':
../../src/FSConnServ.c:166:6: error: 'fd_mask' undeclared (first use in this function)
../../src/FSConnServ.c:166:6: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Daniel Stone <daniel@fooishbar.org>